

export const ADD_NEW_CATEGORY_REQUEST = "ADD_NEW_CATEGORY_REQUEST";
export const ADD_NEW_CATEGORY_REQUEST_FAILURE = "ADD_NEW_CATEGORY_REQUEST_FAILURE";

export const GET_ALL_CATEGORY_REQUEST="GET_ALL_CATEGORY_REQUEST";
export const GET_ALL_CATEGORY_REQUEST_SUCESS="GET_ALL_CATEGORY_REQUEST_SUCESS";
export const GET_ALL_CATEGORY_REQUEST_FAILURE="GET_ALL_CATEGORY_REQUEST_FAILURE";

export const UPDATE_CATEGORY_REQUEST = "UPDATE_CATEGORY_REQUEST";
export const UPDATE_CATEGORY_REQUEST_SUCESS ="UPDATE_CATEGORY_REQUEST_SUCESS";
export const UPDATE_CATEGORY_REQUEST_FAILURE = "UPDATE_CATEGORY_REQUEST_FAILURE";

export const GET_CATEGORY_REQUEST_SUCESS_BYID="GET_CATEGORY_REQUEST_SUCESS_BYID";
export const GET_CATEGORY_REQUEST_FAILURE_BYID="GET_CATEGORY_REQUEST_FAILURE_BYID";