

export const ADD_NEW_LOCATION_REQUEST = "ADD_NEW_LOCATION_REQUEST";
export const ADD_NEW_LOCATION_REQUEST_FAILURE = "ADD_NEW_LOCATION_REQUEST_FAILURE";

export const GET_ALL_LOCATION_REQUEST="GET_ALL_LOCATION_REQUEST";
export const GET_ALL_LOCATION_REQUEST_SUCESS="GET_ALL_LOCATION_REQUEST_SUCESS";
export const GET_ALL_LOCATION_REQUEST_FAILURE="GET_ALL_LOCATION_REQUEST_FAILURE";

export const UPDATE_LOCATION_REQUEST = "UPDATE_CATEGORY_REQUEST";
export const UPDATE_LOCATION_REQUEST_SUCESS ="UPDATE_LOCATION_REQUEST_SUCESS";
export const UPDATE_LOCATION_REQUEST_FAILURE = "UPDATE_LOCATION_REQUEST_FAILURE";

export const GET_LOCATION_REQUEST_SUCESS_BYID="GET_LOCATION_REQUEST_SUCESS_BYID";
export const GET_LOCATION_REQUEST_FAILURE_BYID="GET_LOCATION_REQUEST_FAILURE_BYID";