

export const  ADD_NEW_USER_REQUEST="ADD_NEW_USER_REQUEST";
export const ADD_NEW_USER_REQUEST_FAILURE="ADD_NEW_USER_REQUEST_FAILURE";

export const USER_LOGIN_REQUEST="USER_LOGIN_REQUEST";
export const USER_LOGIN_REQUEST_FAILURE="USER_LOGIN_REQUEST_FAILURE";

export const GET_ALL_USER_REQUEST="GET_ALL_USER_REQUEST";
export const GET_ALL_USER_REQUEST_SUCESS="GET_ALL_USER_REQUEST_SUCESS";
export const GET_ALL_USER_REQUEST_FAILURE="GET_ALL_USER_REQUEST_FAILURE";


export const GET_SINGLE_USER="GET_SINGLE_USER";


export const USER_UPDATE="USER_UPDATE";

export const LOGOUT_REQUEST="LOGOUT_REQUEST";

 